name: deploy

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
    
jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # NestJS에 적합한 Node.js 버전
      
      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sandburg .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create prod.env file
        run: |
          echo '${{ secrets.PROPERTIES_PROD }}' >> prod.env
          
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ubuntu
          script: |
            #!/bin/bash
            # Stop existing container if it exists
            docker stop your-container-name || true
            docker rm your-container-name || true
            
            # Run new container with environment variables
            sudo docker stop sandburg
            sudo docker rm sandburg
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/sandburg
            sudo docker run -d --name sandburg --network sandburg -P ${{ secrets.DOCKER_USERNAME }}/sandburg
            sudo docker image prune -f
