name: deploy

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
    
jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Create .prod.env file
        run: |
          echo '${{ secrets.PROPERTIES_PROD }}' > .prod.env

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sandburg .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sandburg

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ubuntu
          script: |
            sudo docker stop sandburg || true
            sudo docker rm sandburg || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/sandburg
            sudo docker run -d -p 3000:3000 -e NODE_ENV=production --name sandburg --network sandburg ${{ secrets.DOCKER_USERNAME }}/sandburg
            sudo docker image prune -f
